
services:

  web:
    build: .
    image: catanddog_app
    command: gunicorn CatAndDog.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env.dev
    volumes:
      - .:/app   #только в dev
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
      - redis
    expose:
      - 8000

  db:
    image: postgres:15
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  celery_worker:
    build: .
    command: celery -A CatAndDog worker -l info -E
    env_file:
      - .env.dev
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
      - db

  celery_beat:
    build: .
    command: celery -A CatAndDog beat -l info
    env_file:
      - .env.dev
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
      - db

  flower:
    build: .
    command: celery -A CatAndDog flower --port=5555
    env_file:
      - .env.dev
    ports:
      - "5555:5555"
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"   # 👈 dev порт
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: