# Generated by Django 5.2.5 on 2026-02-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_post_photo_remove_post_video_postmedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author_comm',
        ),
    ]
