# Generated by Django 5.2.5 on 2026-03-23 16:54
from apps.news.utils.validators import validate_media_type, validate_file_size
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_user_comment_author_comm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(upload_to='posts/%Y/%m/%d/', validators=[validate_media_type, validate_file_size]),
        ),
    ]
