# Generated by Django 5.2.5 on 2025-11-08 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_comment_options_remove_post_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_publiched',
            new_name='is_published',
        ),
    ]
