# Generated by Django 5.2.5 on 2025-11-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_post_slug_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
